# k8s/04-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: birthday-app-ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: birthday-app-service
      port:
        number: 80
